<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-2513UC9B" ignored="0" name="Default test" tests="9" failures="1" timestamp="18 Jul 2022 11:41:48 GMT" time="6.524" errors="0">
  <testcase name="@AfterMethod takeScreenshotOnFailure" time="0.0" classname="test.LoginPageTestClass">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at test.LoginPageTestClass.takeScreenshotOnFailure(LoginPageTestClass.java:102)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @AfterMethod takeScreenshotOnFailure -->
  <testcase name="@AfterMethod takeScreenshotOnFailure" time="0.0" classname="test.LoginPageTestClass">
    <skipped/>
  </testcase> <!-- @AfterMethod takeScreenshotOnFailure -->
  <testcase name="@AfterMethod takeScreenshotOnFailure" time="0.0" classname="test.LoginPageTestClass">
    <skipped/>
  </testcase> <!-- @AfterMethod takeScreenshotOnFailure -->
  <testcase name="@AfterMethod takeScreenshotOnFailure" time="0.0" classname="test.LoginPageTestClass">
    <skipped/>
  </testcase> <!-- @AfterMethod takeScreenshotOnFailure -->
  <testcase name="@AfterMethod takeScreenshotOnFailure" time="0.0" classname="test.LoginPageTestClass">
    <skipped/>
  </testcase> <!-- @AfterMethod takeScreenshotOnFailure -->
  <testcase name="@AfterMethod takeScreenshotOnFailure" time="0.0" classname="test.LoginPageTestClass">
    <skipped/>
  </testcase> <!-- @AfterMethod takeScreenshotOnFailure -->
  <testcase name="@AfterMethod takeScreenshotOnFailure" time="0.0" classname="test.LoginPageTestClass">
    <skipped/>
  </testcase> <!-- @AfterMethod takeScreenshotOnFailure -->
  <testcase name="@AfterMethod takeScreenshotOnFailure" time="0.0" classname="test.LoginPageTestClass">
    <skipped/>
  </testcase> <!-- @AfterMethod takeScreenshotOnFailure -->
  <testcase name="@AfterMethod takeScreenshotOnFailure" time="0.0" classname="test.LoginPageTestClass">
    <skipped/>
  </testcase> <!-- @AfterMethod takeScreenshotOnFailure -->
  <testcase name="userLoggedIn" time="0.008" classname="test.LoginPageTestClass">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at test.LoginPageTestClass.userLoggedIn(LoginPageTestClass.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- userLoggedIn -->
  <testcase name="verifyThatUserLoggedInSuccessfully" time="0.0" classname="test.LoginPageTestClass">
    <skipped/>
  </testcase> <!-- verifyThatUserLoggedInSuccessfully -->
  <testcase name="verifyThatUserCanOpenANewAccount" time="0.0" classname="test.LoginPageTestClass">
    <skipped/>
  </testcase> <!-- verifyThatUserCanOpenANewAccount -->
  <testcase name="verifyThatTheNewAccountNumberIsDisplayed" time="0.0" classname="test.LoginPageTestClass">
    <skipped/>
  </testcase> <!-- verifyThatTheNewAccountNumberIsDisplayed -->
  <testcase name="verifyTotalAmountWithTheUser" time="0.0" classname="test.LoginPageTestClass">
    <skipped/>
  </testcase> <!-- verifyTotalAmountWithTheUser -->
  <testcase name="getTheTotalTransactionsInADateRange" time="0.0" classname="test.LoginPageTestClass">
    <skipped/>
  </testcase> <!-- getTheTotalTransactionsInADateRange -->
  <testcase name="verifyThatTheUserCanVerifyForLoan" time="0.0" classname="test.LoginPageTestClass">
    <skipped/>
  </testcase> <!-- verifyThatTheUserCanVerifyForLoan -->
  <testcase name="verifyTheLoanStatus" time="0.0" classname="test.LoginPageTestClass">
    <skipped/>
  </testcase> <!-- verifyTheLoanStatus -->
  <testcase name="clickOnLogOutLink" time="0.0" classname="test.LoginPageTestClass">
    <skipped/>
  </testcase> <!-- clickOnLogOutLink -->
</testsuite> <!-- Default test -->
